[client] mbti 테스트 프리뷰 페이지 ui, 좋아요 기능 구현
Mong-Bit/mongbit_fe_next_v2 pull request #23
Opened 2024-04-28 01:28 UTC by Moorisong

1. mbti 테스트 상세 정보 표시, 댓글 영역 등 ui 구현
2. 좋아요 추가 / 좋아요 삭제 기능 구현

**링크 복사, 공유, 댓글 추가/수정/삭제 기능은 추후 구현 예정입니다.**

2024-04-28 16:45 UTC, the1975 requested changes

2024-04-28 16:45 UTC, the1975 commented on apps/client/app/mbtiTest/preview/[id]/page.tsx
> +async function getData(url: RouteMbtiTest.getMbtiTestDataProp) {
이정도는 namespace 안쓰고 그냥 내부 interface 써도 됩니다. 
그리고 네이밍도 get~ 으로 시작하는건 함수만 사용하는게 좋겠네요.
그냥 
```ts
getData(url: string)
```
이 오히려 좋아보이네요.

2024-04-28 16:45 UTC, the1975 commented on apps/client/app/mbtiTest/preview/[id]/page.tsx
> +  const mbtiTestCommentData = await getData(`/api/v1/test/comments/${params.id}`).then(
API들은 전부 then 구문까지 묶어서 `services` scope로 묶어주세요.

2024-04-28 16:45 UTC, the1975 commented on apps/client/components/base/MyHeader.tsx
> +  const clickHeaderButton = (type: string, { showSideMenu, setShowSideMenu }: CommonStyledComponents.SideMenuState) => {
핸들러용 함수면 차라리 handleClickHeaderButton이 역할 파악에 용이할 것 같네요

2024-04-28 16:45 UTC, the1975 commented on apps/client/components/base/SideMenu.tsx
> +                <Link href="/mbtiTest/latest" onClick={hideSideMenu}>
URL에는 camelCase를 잘 쓰지 않습니다 kebab-case로 사용하는게 좋을 것 같네요.

2024-04-28 16:45 UTC, the1975 commented on apps/client/containers/previewMbtiTest/index.tsx
> +          <ContentText padding="0.2rem 0 0 0" key={e + id}>
e는 무슨 데이터를 의미하는건가요? 이벤트인가요?
그리고 key가 `e + id` 인데, string + number 타입을 연산하는것 보다는 string literal로 넣어주는게 좋겠습니다.

2024-04-28 16:45 UTC, the1975 commented on apps/client/utils/common.ts
> +    return `${diffYears}년 전`;
이정도면 switch-case 쓰세요.

2024-04-28 16:45 UTC, the1975 commented on apps/client/utils/types.d.ts
> +  type LikeState = booleanl;
booleanl 타입은 뭔가요? 이거 빌드에러 안나나요?

2024-04-28 16:45 UTC, the1975 commented on apps/client/utils/util.js
> -// export function formatTimeDifference(dateString) {
파일을 아예 안쓸거면 지워주세요.

2024-04-28 23:06 UTC, Moorisong commented on apps/client/components/base/MyHeader.tsx
> +  const clickHeaderButton = (type: string, { showSideMenu, setShowSideMenu }: CommonStyledComponents.SideMenuState) => {
감사합니다. 다음과 같이 반영했습니다.
- 27d86ec7148de579e86ab0c0cc9e4bf0456d70c9

2024-04-28 23:26 UTC, Moorisong commented on apps/client/app/mbtiTest/preview/[id]/page.tsx
> +  const mbtiTestCommentData = await getData(`/api/v1/test/comments/${params.id}`).then(
오 ㅎㅎ 감사합니다. services 스코프 내에서 리턴하도록 하겠습니다.
수정 완료했습니다.
- 634f874b6881aadae1b705ac94e70725063b36d8

2024-04-29 00:39 UTC, Moorisong commented on apps/client/components/base/SideMenu.tsx
> +                <Link href="/mbtiTest/latest" onClick={hideSideMenu}>
헉 그렇네요! 감사합니다. 반영 하였습니다.
- 2b3f9345eba01de142bd9436ae752e440a8b27ec

2024-04-29 00:40 UTC, Moorisong commented on apps/client/utils/types.d.ts
> +  type LikeState = booleanl;
수정 했습니다. 감사합니다.
- 4c36299da36fcbe14d8817acbc0be4b6de0065fb

2024-04-29 00:42 UTC, Moorisong commented on apps/client/utils/util.js
> -// export function formatTimeDifference(dateString) {
@the1975 추후 다른 페이지 개발 시 참고될 함수들이라 제거는 못하고 주석처리 해두었습니다. 
이런 경우에는 어떻게 처리하는 것이 좋을까요?
조언 주시면 감사하겠습니다.

2024-04-29 03:39 UTC, Moorisong commented on apps/client/containers/previewMbtiTest/index.tsx
> +          <ContentText padding="0.2rem 0 0 0" key={e + id}>
e는 element의 줄임말로 사용했습니다. 이벤트와 헷갈릴 수 있겠네요. ele로 변경하는 것이 좋을까요? 
- ecd12bbcf79991addfae7ec9ac34ca51a005ba2d

2024-04-29 03:49 UTC, Moorisong commented on apps/client/utils/common.ts
> +    return `${diffYears}년 전`;
넵. 반영하였습니다.
- 2da404e9a23fbf9f12f3ed2f7791b07bd4c5100d

2024-04-29 03:54 UTC, Moorisong commented on apps/client/app/mbtiTest/preview/[id]/page.tsx
> +async function getData(url: RouteMbtiTest.getMbtiTestDataProp) {
감사합니다. 전체 타입 정리할 시간을 가질 계획인데 그때 get으로 시작하는 건 함수에만 적용하도록 전부 수정하겠습니다!
- 917cc9a538d21b3654c60ef45f9a303e86df5eb2

2024-04-29 06:21 UTC, the1975 commented on apps/client/app/mbtiTest/preview/[id]/page.tsx
> +  const mbtiTestCommentData = await getData(`/api/v1/test/comments/${params.id}`).then(
그게 아니고 
```ts
await getData(`/api/v1/tests/test/${params.id}`).then((response) => response?.dataList);
```
을
```ts
await getMbtiTestData()
```
형식으로 사용할 수 있도록 `services` 단으로 넣어두는게 좋단 의미입니다.

2024-04-29 06:21 UTC, the1975 commented on apps/client/containers/previewMbtiTest/index.tsx
> +          <ContentText padding="0.2rem 0 0 0" key={e + id}>
el 이면 충분합니다

2024-04-29 06:21 UTC, the1975 commented on apps/client/utils/util.js
> -// export function formatTimeDifference(dateString) {
그럼 그냥 활성화 시켜두는게 나아보입니다. 유틸이라는건 만들어두고 언제든 가져올 수 있도록 하는것에 의의를 두는 거라서요.

2024-04-29 06:41 UTC, Moorisong commented on apps/client/utils/util.js
> -// export function formatTimeDifference(dateString) {
감사합니다. 활성화 해두겠습니다.
- f7ef5418a33ba5ed9609c248c83ebd857f576d5b

2024-04-29 06:42 UTC, Moorisong commented on apps/client/containers/previewMbtiTest/index.tsx
> +          <ContentText padding="0.2rem 0 0 0" key={e + id}>
넵 감사합니다! 매개변수 명 모두 el로 변경했습니다.
- 98bb5e61084f291cdc35d2583a2e9256cc076586

2024-04-29 09:39 UTC, Moorisong commented on apps/client/app/mbtiTest/preview/[id]/page.tsx
> +  const mbtiTestCommentData = await getData(`/api/v1/test/comments/${params.id}`).then(
넵 감사합니다. 다음과 같이 반영했습니다.
- 5d6d98aade5f4491220f39f9c44b2d8a87971963

2024-04-29 14:32 UTC, the1975 approved these changes

2024-04-29 14:32 UTC, lucy0701 approved these changes

2024-04-29 14:48 UTC, merged