[admin] Fix/admin/apply pr comments
Mong-Bit/mongbit_fe_next_v2 pull request #46
Opened 2024-05-06 13:15 UTC by lucy0701

1. next.js -> error 라우팅 (필요없어진 paths 삭제)
2. EOL -> lint 수정 및 미반영 부분 반영
3. 커스텀 훅 : 한 곳에서만 사용하는 함수 컴포넌트 내부로 이동 후 삭제
4. useAsyncAction 수정
5. interceptor : axios / interceptor 사용하여 전역 에러처리

2024-05-06 13:16 UTC, lucy0701 reviewed
커밋 되돌리기는... 실수로 커밋 되돌리기를 눌러 복구한 부분이라 안보셔도 됩니다..

2024-05-06 13:55 UTC, lucy0701 reviewed
:-)

2024-05-06 13:55 UTC, lucy0701 commented on apps/admin/services/index.ts
> +apiBe_v1.interceptors.response.use(
interceptors 처리 부분입니다

2024-05-06 13:55 UTC, lucy0701 commented on apps/admin/app/admin/error.tsx
> +
error.tsx 입니다

2024-05-12 04:43 UTC, lucy0701 reviewed
useAsyncAction() 함수 관련 피드백 반영

2024-05-12 04:43 UTC, lucy0701 commented on apps/admin/hooks/useAsyncAction.ts
> +  return [isLoading, executeAsyncAction] as const;
반환 타입 변경 했습니다

2024-05-12 04:43 UTC, lucy0701 commented on apps/admin/hooks/useAsyncAction.ts
> +const useAsyncAction = <T>(actionFunction: (args: T) => Promise<void>, args?: T) => {
프롭을 useAsyncAction()함수가 직접 받도록 변경

2024-05-12 04:43 UTC, lucy0701 commented on apps/admin/containers/ContentsComponent/index.tsx
> +  const [isLoading, executeGetContents] = useAsyncAction(getContents, { page: pageNum, size: pageSize });
실행 함수명 변경 ->  적당한 네이밍이 안 떠올라 앞에 execute를 붙였습니다..

2024-05-12 07:58 UTC, the1975 requested changes

2024-05-12 07:58 UTC, the1975 commented on apps/admin/containers/ContentsComponent/index.tsx
> +  const [pageNum, setPage] = useState(0);
{state}와 set{State}는 네이밍이 동일한게 좋습니다.

const [a, setA] = useState

2024-05-12 07:58 UTC, the1975 commented on apps/admin/containers/ContentsComponent/index.tsx
> +  const [isLoading, executeGetContents] = useAsyncAction(getContents, { page: pageNum, size: pageSize });
이거 getContents 자체에서 이미 로직을 따로 래핑했으면 굳이 useAsyncAction에서 executeGetContents로 loading을 위해서 또 래핑할 필요가 있을까요?

async 함수가 중첩으로 들어가있는 구조네요.

2024-05-12 07:58 UTC, the1975 commented on apps/admin/containers/Dashboard/LatestContentCard/index.tsx
> +          createDate: content.data.test.createDate as string,
as 사용한 이유가 있을까요? `getContentAPI` response 타입을 먼저 지정해주면 해결될 것 같습니다.

2024-05-12 07:58 UTC, the1975 commented on apps/admin/containers/KakaoLogin/KakaoAuthHandle/index.tsx
> +          alert('접근 권한이 없습니다. 로그인페이지로 이동합니다.');
window.alert인가요? antd의 얼럿 사용해도 될 것 같네요.

2024-05-12 07:58 UTC, the1975 commented on apps/admin/hooks/useAsyncAction.ts
> +  return [isLoading, executeAsyncAction] as const;
여기서 as const로 사용한 이유가 있나요? `useAsyncAction` 함수의 return type에서 지정해주는건 안되는지 궁금합니다.

2024-05-12 07:58 UTC, the1975 commented on apps/admin/hooks/useCounts.ts
> +    const sortedData = dateRangeCounts.data.sort((a, b) => {
sort를 사용해서 `sortedData` 에 담아도 의미가 없는 듯 하네요. sort 메서드는 mutable 한 메서드라서 `dateRangeCounts.data` 를 오염시킵니다. 정확하게는 `[...dateRangeCounts.data].sort()` 로 사용해야 합니다.

2024-05-12 07:58 UTC, the1975 commented on apps/admin/hooks/useSaveMbti.ts
> +        alert('테스트 업로드 완료');
여기 alert들도 antd 내장된걸 사용하면 좋겠네요.

2024-05-12 11:29 UTC, lucy0701 commented on apps/admin/hooks/useAsyncAction.ts
> +  return [isLoading, executeAsyncAction] as const;
return type에서 지정하는 것은 가능합니다.
``` ts
  return [
    isLoading,
    executeAsyncAction
  ] as [boolean, () => Promise<void>];
```

**as const를 사용한 이유**
- 객체 : 각 프로퍼티에 직접적으로 타입이 부여가 가능, 순서와 상관 없음
- 배열 : 각 인덱스에 타입을 부여,  순서가 변경 혹은 요소가 추가/제거 될때 새롭게 정의를 해야하므로 유지보수에서   불리하다고 생각했습니다.
- 물론 코드가 추가 되거나 변경 될 가능성은 적으나, 배열의 경우 정확성을 높이기 위해선 as const가 유용하다고 생각했습니다.

그리고 솔직하게 말씀 드리자면, 가독성 면에서 as const를 선택한게 가장 큽니다.

2024-05-15 13:13 UTC, the1975 commented on apps/admin/hooks/useAsyncAction.ts
> +  return [isLoading, executeAsyncAction] as const;
제가 궁금한건
```ts
const useAsyncAction = <T>(actionFunction: (args: T) => Promise<void>, args?: T): [boolean, () => Promise<void>] => {
```
요렇게 지정하면 안되는건지 궁금해서요

2024-05-15 13:15 UTC, the1975 commented on apps/admin/hooks/useCounts.ts
> +        name: VISITS,
이런것들까지 상수화 할 필요가 있나요? 이거 타입으로 체크하면 안되는건지

2024-05-15 16:11 UTC, lucy0701 commented on apps/admin/containers/Dashboard/LatestContentCard/index.tsx
> +          createDate: content.data.test.createDate as string,
- 예전에 오류가 나서 했었습니다. response 타입 설정 확인 후 삭제했습니다
[ac92d72](https://github.com/Mong-Bit/mongbit_fe_next_v2/pull/46/commits/ac92d729ee3a9c3aa12c0a4539105212c1bdb735)

2024-05-15 16:17 UTC, lucy0701 commented on apps/admin/hooks/useCounts.ts
> +    const sortedData = dateRangeCounts.data.sort((a, b) => {
생각하지 못 했던 부분입니다! 감사합니다. 변경 완료 했습니다
[0aaeb22](https://github.com/Mong-Bit/mongbit_fe_next_v2/pull/46/commits/0aaeb22946ba58eb423cd52db42b35212071997e)

2024-05-16 04:16 UTC, lucy0701 commented on apps/admin/hooks/useCounts.ts
> +        name: VISITS,
타입으로 변경 완료했습니다! 
[446356d](https://github.com/Mong-Bit/mongbit_fe_next_v2/pull/46/commits/446356d5c5325a574742bfdae7049f2d33244907)

2024-05-16 04:48 UTC, lucy0701 commented on apps/admin/containers/ContentsComponent/index.tsx
> +  const [isLoading, executeGetContents] = useAsyncAction(getContents, { page: pageNum, size: pageSize });
일단 기존 사용하던 커스텀 훅 관련해서는 직접 로딩을 반환하도록 변경했습니다.
[4bef0c5](https://github.com/Mong-Bit/mongbit_fe_next_v2/pull/46/commits/4bef0c5c1112712746451d09549ae1cddb6fcb37)

추가로 useAsyncAction() 함수 릭팩토링 진행하겠습니다

2024-05-16 10:49 UTC, lucy0701 commented on apps/admin/hooks/useAsyncAction.ts
> +  return [isLoading, executeAsyncAction] as const;
useQuery () 함수로 변경하면서 반환 타입 적용했습니다!! 

[dfce1d2](https://github.com/Mong-Bit/mongbit_fe_next_v2/pull/46/commits/dfce1d250ca0980e354886de37b418c1d4c303fc)

2024-05-16 13:41 UTC, lucy0701 commented on apps/admin/containers/KakaoLogin/KakaoAuthHandle/index.tsx
> +          alert('접근 권한이 없습니다. 로그인페이지로 이동합니다.');
적용 완료 했습니다!

[cc0c873](https://github.com/Mong-Bit/mongbit_fe_next_v2/pull/46/commits/cc0c8736d2e49407711da13b3821b13079ee6183)

2024-05-16 13:41 UTC, lucy0701 commented on apps/admin/hooks/useSaveMbti.ts
> +        alert('테스트 업로드 완료');
적용 완료 했습니다!
[1d39aa2](https://github.com/Mong-Bit/mongbit_fe_next_v2/pull/46/commits/1d39aa28482f21743d0e5236005f09ad41ad3d0c)

2024-05-16 16:00 UTC, the1975 commented on apps/admin/hooks/useContent.ts
> +    const response = await getContentAPI(testId);
getContent 내용을 useQuery를 사용해서 적용해보면 괜찮겠네요.

2024-05-16 16:01 UTC, the1975 commented on apps/admin/containers/Dashboard/TopContentsCard/index.tsx
> +          <DashboardSelect handleChange={handleChange} defaultValue={TOP_COUNT_OPTIONS} />
여기서 prop이름은 handleChange보다는 onChange가 맞아보입니다.
onChange={handleChange}

2024-05-16 16:02 UTC, the1975 commented on apps/admin/components/layout/AntdProvider/index.tsx
> +        algorithm: isDarkMode ? theme.darkAlgorithm : theme.defaultAlgorithm,
얼럿 메세지 다크모드 잘 적용 되나요?

2024-05-16 16:10 UTC, the1975 commented on apps/admin/hooks/useQuery.ts
> +  return [data, fetchData, isLoading];
여기선 객체로 반환하는게 좋습니다. fetchData를 사용하지 않는 경우도 있으니까요

2024-05-16 16:12 UTC, the1975 commented on apps/admin/hooks/useQuery.ts
> +  params: S,
params가 변경되었을 때 처리도 안에 같이 들어가야 할 것 같네요.

2024-05-16 17:14 UTC, lucy0701 commented on apps/admin/components/layout/AntdProvider/index.tsx
> +        algorithm: isDarkMode ? theme.darkAlgorithm : theme.defaultAlgorithm,
넵!

2024-05-16 17:15 UTC, lucy0701 commented on apps/admin/hooks/useSaveMbti.ts
> +          isOn: true,
메세지가 켜지도록 하는 의미로 isOn이라고 했는데 마땅한 네이밍이 생각 안났습니다

2024-05-16 17:17 UTC, the1975 commented on apps/admin/hooks/useSaveMbti.ts
> +          isOn: true,
나중에 값을 넣으면 그냥 열리도록 개선하면 좋을 듯 합니다.

2024-05-16 17:25 UTC, lucy0701 commented on apps/admin/containers/Dashboard/TopContentsCard/index.tsx
> +          <DashboardSelect handleChange={handleChange} defaultValue={TOP_COUNT_OPTIONS} />
변경 완료 했습니다 
[b3a6b38](https://github.com/Mong-Bit/mongbit_fe_next_v2/pull/46/commits/b3a6b389ab47e54dd8256b44febb6f2d4f413b14)

2024-05-16 17:26 UTC, lucy0701 commented on apps/admin/types/options.ts
> +export type OptionType = {
변경 완료했습니다 
[be98c9c](https://github.com/Mong-Bit/mongbit_fe_next_v2/pull/46/commits/be98c9c951793f9596c560e530ad7992bd0fce96)

2024-05-16 17:26 UTC, the1975 approved these changes

2024-05-16 17:27 UTC, merged