[client] mbti 테스트 진행 페이지 구현
Mong-Bit/mongbit_fe_next_v2 pull request #52
Opened 2024-05-09 06:13 UTC by Moorisong

**1. 화면** 
   ![image](https://github.com/Mong-Bit/mongbit_fe_next_v2/assets/64249489/11f1ff8e-c20d-410f-869a-000deab2dc6a)

**2. 테스트 진행 페이지 진입 방법**
  -  테스트 프리뷰 페이지에서 '테스트 시작' 버튼 클릭 시 테스트 진행 페이지로 이동

**3. 질문지 구성 및 응답 value**
  - 질문지 개수 : 12개
  - 긍정 응답지 value : 1
  - 부정 응답지 value : -1

**4. score 배열 생성 로직**
  - 질문지 응답 값은 긍정(1), 부정(-1)으로 나누어져있다.
  - 12개 질문의 응답을 클릭할때마다 응답 값을 inputArr 배열에 담는다.
     -  ex) [1, -1, 1, 1 ...]
  - inputArr 배열을 score 배열로 가공한다.
    - ex) [-3, 3, 3, -1]
  - score 배열을 recoil state에 담는다.

**5. 참고 사항** 
 - Typescript 적용은 수정님 타입 수정 작업이 끝난 후에 진행할 예정입니다.
 - 이슈 : #39

2024-05-10 07:48 UTC, the1975 requested changes

2024-05-10 07:48 UTC, the1975 commented on apps/client/app/GlobalStateRoot.jsx
> +            prop !== 'lineHeight'
이거 이렇게 관리하면 안되지 않나요..?

2024-05-10 07:48 UTC, the1975 commented on apps/client/app/mbti-test/on/[id]/page.tsx
> +  return <OnMbtiTest data={mbtiTestData?.dataList.test} />;
라우트가 on으로 중간에 들어가면 안되지 않을까요? [id] 하위에서 라우트가 생성되어야 할 것 같네요.

2024-05-10 07:48 UTC, the1975 commented on apps/client/components/base/SideMenu.tsx
> +};
이정도는 그냥 컴포넌트 내부에서 정의해도 됩니다. 오히려 prop으로 넘겨주는게 많아서요.

2024-05-10 07:48 UTC, the1975 commented on apps/client/components/base/SideMenu.tsx
> +export function SideMenu({ show }: CommonStyledComponents.SideMenuProp) {
show 객체의 네이밍이 명확하지 않습니다.
그리고 useState의 setter를 직접 내려주는 패턴도 모듈화에 절대 좋지 않습니다.

isShow 또는 show, isShown 으로 내려주고, onHide 와 같은 이벤트로 부모로 올려주는 패턴을 사용하세요.
그리고 recoil을 적용한 것 같은데, 이런 상태값들을 prop으로 관리하는 이유가 있나요?

2024-05-10 07:48 UTC, the1975 commented on apps/client/components/base/SideMenu.tsx
> +  setLogIn: CommonStyledComponents.SetLogIn,
보통 로그인을 명사로 사용할 땐 Login 으로 사용합니다 Log In은 동사로 사용하구요.

2024-05-10 07:48 UTC, the1975 commented on apps/client/components/base/SideMenu.tsx
> +      <SideMenuGrayDiv height={height.toString()} />
이거 height number로는 동작 안하나요?

2024-05-10 07:48 UTC, the1975 commented on apps/client/components/base/SideMenu.tsx
> +                <Link href="/mbti-test/latest" onClick={hideSideMenu}>
https://github.com/Mong-Bit/mongbit_fe_next_v2/blob/dev_client/apps/client/constants/paths.ts#L1

여기에 Path 정의되어 있지 않나요? 이걸 재사용해야 할 것 같은데요.

2024-05-10 07:48 UTC, the1975 commented on apps/client/components/ui/types.d.ts
> +declare namespace Ui {
d.ts 파일과 namespace로 사용하는 이유가 있나요?

2024-05-10 07:48 UTC, the1975 commented on apps/client/components/ui/types.d.ts
> +    mbtiTestData: Model.MbtiTest[] | undefined;
```ts
mbtiTestData?: Model.MbtiTest[]
```
는 안되는건가요?

2024-05-10 07:48 UTC, the1975 commented on apps/client/containers/onMbtiTest/index.tsx
> +      {questions.map((el, i) => {
`el` 네이밍 의미가 뭔가요? questions 요소면 question이 맞지 않나요?

2024-05-10 07:48 UTC, the1975 commented on apps/client/containers/previewMbtiTest/index.tsx
> +            테스트 시작 &gt;
위에는 `{'< 이전 질문'}` 이고 여기는 `테스트 시작 &gt;` 이고 한쪽으로 통일해서 사용하면 좋겠네요.

2024-05-12 01:33 UTC, Moorisong commented on apps/client/components/base/SideMenu.tsx
> +};
감사합니다. 반영했습니다.
- 6ecb7e495553f8bf6f916162f818e0794a93fa97

2024-05-12 01:36 UTC, Moorisong commented on apps/client/components/base/SideMenu.tsx
> +};
감사합니다. 반영했습니다.
- 6ecb7e495553f8bf6f916162f818e0794a93fa97

2024-05-12 01:37 UTC, Moorisong commented on apps/client/app/mbti-test/on/[id]/page.tsx
> +  return <OnMbtiTest data={mbtiTestData?.dataList.test} />;
라우트 변경 및 상수화 하였습니다.
- 2a6713a55dd201ef540a79849030140e1f7fe964

2024-05-12 01:38 UTC, Moorisong commented on apps/client/components/base/SideMenu.tsx
> +                <Link href="/mbti-test/latest" onClick={hideSideMenu}>
넵 적용했습니다!

2024-05-12 01:39 UTC, Moorisong commented on apps/client/components/ui/types.d.ts
> +    mbtiTestData: Model.MbtiTest[] | undefined;
오 감사합니다. 현재 수정님이 진행 중인 타입스크립트 작업이 끝난 후 적용하도록 하겠습니다.

2024-05-12 01:45 UTC, Moorisong commented on apps/client/containers/previewMbtiTest/index.tsx
> +            테스트 시작 &gt;
감사합니다. 반영했습니다.
- 05bb8f656b7f5cb6f42f3e2b3c0ff425bb3c8e64

2024-05-12 01:51 UTC, Moorisong commented on apps/client/hooks/useScoreState.ts
> +export const useInitializeState = () => {
@the1975  안그래도 여쭤보고 싶었어요.

재사용하지는 않지만 가독성이 높아진다는 장점 때문에 훅으로 분리해보았는데,
복잡한 로직이나 추상화를 정리할 때도 훅으로 빼서 사용한다고 들었는데,
동시에 무분멸한 커스텀 훅의 사용도 좋지 않다고 들어서요.

커스텀 훅을 사용하는 명확한 기준에 대해 좀 궁금했습니다.
조언 주시면 참고해서 수정하겠습니다!

2024-05-12 01:54 UTC, Moorisong commented on apps/client/containers/onMbtiTest/index.tsx
> +      {questions.map((el, i) => {
일전에 말씀드렸듯이 element의 el 입니다.
반복 함수의 매개변수 명을 간결하고 일관되게 통일하기 위해 보통 'el'로 사용하고 있습니다.

2024-05-12 01:55 UTC, Moorisong commented on apps/client/components/ui/types.d.ts
> +declare namespace Ui {
이건 제가 너무 잘못 생각한 것 같아요.
단순히 import 문을 줄이는 등 리소스 낭비를 줄이자는 취지로 사용했는데
예상치 못한 상황이 많이 일어나는 것 같습니다.
모두 수정하려고 합니다.

2024-05-12 02:16 UTC, Moorisong commented on apps/client/components/base/SideMenu.tsx
> +  setLogIn: CommonStyledComponents.SetLogIn,
넵 감사합니다!
- 091dcfbe1fefcd360e3e6e5117fb51bd5baee1fc

2024-05-12 07:21 UTC, the1975 commented on apps/client/containers/onMbtiTest/index.tsx
> +      {questions.map((el, i) => {
음 개인적으로는 통일성보다 코드를 부분적으로 봤을 때의 가독성을 더 중요시하는 편이라서요.
el보다는 plural한 리스트 변수명 하위의 순회에서는 el보다는 singular 형태가 맞아보이긴 합니다.
하지만 이건 취향 차이긴 하니 넘어갈게요. 대체적으로 el로 통일하는 경우는 잘 보지는 못했습니다.

2024-05-12 07:24 UTC, the1975 commented on apps/client/hooks/useScoreState.ts
> +export const useInitializeState = () => {
명확한 기준은 없습니다. 정답도 없구요.
다만 이정도 로직을 한군데서만 사용하는데 굳이 빼야하나 하고 여쭤본겁니다.

2024-05-12 07:35 UTC, the1975 requested changes

2024-05-12 07:35 UTC, the1975 commented on apps/client/components/MbtiTestContent/index.tsx
> +      <Link href={PATHS_TEST_ID('649a7bccaa04db61384808c5', PATHS.PREVIEW)}>
`PATHS_TEST_ID` 이건 함수인건가요? 보통 함수명을 이렇게 안짓지 않나요?
상수인지 함수인지 헷갈릴 것 같네요.

2024-05-12 07:35 UTC, the1975 commented on apps/client/components/SideMenu/index.tsx
> +    return router.push('/');
여기 return이 무조건 들어가야 하나요?

2024-05-12 07:35 UTC, the1975 commented on apps/client/containers/onMbtiTest/index.tsx
> +  const { stage, barWidth, setStage, clickHandler } = useUpdateState();
사실 이 훅도 정확히 무슨 역할을 하는건지 네이밍만 봐서는 잘 감이 잡히지 않습니다.
내용을 보니 테스트 스테이지 넘어가면서 핸들링 해주는 역할인 것 같은데.
저 훅 안에있는 내용이 해당 컴포넌트로 다 나와있어도 전혀 문제가 없는 상황이네요.
게다가 여기 한군데밖에 사용할 수 없는 훅이기도 하구요.

단순히 한 컴포넌트의 라인 수를 줄이기 위해서라면 오히려 가독성에서 역효과만 날 것 같습니다. 코드 흐름 파악에서 걸림돌만 되니까요.

2024-05-12 07:35 UTC, the1975 commented on apps/client/utils/common.ts
> +  const token = json ? json.recoil_login[LOGIN.TOKEN_NAME] : '';
로그인 토큰을 세션스토리지에 저장하나요? 쿠키가 아니라?

2024-05-13 00:30 UTC, Moorisong commented on apps/client/containers/onMbtiTest/index.tsx
> +      {questions.map((el, i) => {
조언 감사합니다 ㅎㅎ 좀 더 고민해보겠습니다.

2024-05-13 00:31 UTC, Moorisong commented on apps/client/hooks/useScoreState.ts
> +export const useInitializeState = () => {
음 정답이 없는 부분이라면, 훅 분리에 대한 기준을 먼저 잡아야할 것 같네요. 감사합니다.

2024-05-13 00:36 UTC, Moorisong commented on apps/client/components/SideMenu/index.tsx
> +    return router.push('/');
실수입니다! 제거했습니다. 감사합니다
- 13b555cf714b4d3e37f36cbdc65821f364b6c427

2024-05-13 00:38 UTC, Moorisong commented on apps/client/utils/common.ts
> +  const token = json ? json.recoil_login[LOGIN.TOKEN_NAME] : '';
처음 몽빗을 기획할때 팀원들과 회의했던 내용이었습니다. 
일회성이 짙은 성격 상 쿠키에 저장할 필요가 있을까 싶어 세션으로 정했던건데,
현재 충원된 프론트엔드 팀원과 논의해본 결과 쿠키를 사용하는 방향으로 결정되어 추후 적용 예정입니다.

2024-05-13 00:48 UTC, Moorisong commented on apps/client/containers/onMbtiTest/index.tsx
> +  const { stage, barWidth, setStage, clickHandler } = useUpdateState();
네. 불필요하게 훅으로 분리한 케이스 같습니다. 재사용하는 기능이 아니라면 컴포넌트 내부에서 해결하도록 하겠습니다.
감사합니다. 아래와 같이 반영했습니다!
- 94d0223e7263361bbf6b7f0e40bf70911a47b9de

2024-05-13 00:52 UTC, Moorisong commented on apps/client/components/MbtiTestContent/index.tsx
> +      <Link href={PATHS_TEST_ID('649a7bccaa04db61384808c5', PATHS.PREVIEW)}>
오 그러네요. 아래와 같이 반영해보았습니다.
- a447a813acca9d86f3ab3e45f7133f225efba656

2024-05-13 02:24 UTC, Moorisong commented on apps/client/components/base/SideMenu.tsx
> +export function SideMenu({ show }: CommonStyledComponents.SideMenuProp) {
감사합니다! 모듈화에 더 신경쓰도록 하겠습니다.
사이드 메뉴 show 상태는 recoil state로 업데이트 하였습니다.

- 2f636a75bc12b0a7d0685998391007c9215c5808
- 1e0cd27c4c7fe1c42ca9dde97487a410d3e3c1c8
- 723eb32cddad1cce14af8c4aedf8b332d24f223c

2024-05-13 03:00 UTC, Moorisong commented on apps/client/components/base/SideMenu.tsx
> +      <SideMenuGrayDiv height={height.toString()} />
감사합니다. number로도 동작합니다.
- aba74a5aa8e1a1df678f0f317646067a2b32eafc

2024-05-13 08:33 UTC, Moorisong commented on apps/client/app/GlobalStateRoot.jsx
> +            prop !== 'lineHeight'
스타일드 컴포넌트로 넘겨지는 prop 명이 비표준 css일때 필터링 되도록 조치한 것입니다.
그런데 일반적인 사용법이 아님을 확인하여 다음과 같이 수정하였습니다.

1. StyleSheetManager shouldForwardProp 함수로 1차 필터링 거침(스타일드 매커니즘으로 필터링 됩니다)
2. '$' prefix를 사용하여 추가적으로 필터링 함

- 48a541d37e62010559d3d6e5cd6395fab6a58f75

2024-05-15 12:20 UTC, the1975 requested changes

2024-05-15 12:20 UTC, the1975 commented on apps/client/components/ButtonArea/index.tsx
> +        <L.Flex $flexDirection="column" gap="0.5rem" key={e.text + i}>
`el`로 통일한다고 하지 않았었나요? 여기는 e네요

2024-05-15 12:20 UTC, the1975 commented on apps/client/components/MbtiTestContent/index.tsx
> +      <Link href={GENERATE_PATHS_TEST_ID('649a7bccaa04db61384808c5', PATHS.PREVIEW)}>
이것도 상수인지 함수인지 헷갈립니다. UPPER_SNAKE_CASE는 보통 상수에만 사용합니다. `getTestIDPath()` 와 같은 함수명이 좋습니다.

2024-05-15 12:20 UTC, the1975 commented on apps/client/components/MyHeader/index.tsx
> +      <SideMenu doLogOut={doLogOut} hideSideMenu={hideSideMenu} login={login} />
이거 SideMenu에서 `onLogout` 이런 이벤트형식 네이밍이 좋지않나요?

2024-05-15 12:20 UTC, the1975 commented on apps/client/components/ui/types.d.ts
> +  type Wrap = {
이것들도 React.CSSProperties가 있지 않나요?

2024-05-16 03:44 UTC, Moorisong commented on apps/client/components/ButtonArea/index.tsx
> +        <L.Flex $flexDirection="column" gap="0.5rem" key={e.text + i}>
누락된 부분이 몇개 있었네요. 수정했습니다.
- 123b65e310379dc22c9fb21232e7430017f03ab4

2024-05-16 03:45 UTC, Moorisong commented on apps/client/components/MbtiTestContent/index.tsx
> +      <Link href={GENERATE_PATHS_TEST_ID('649a7bccaa04db61384808c5', PATHS.PREVIEW)}>
넵 다음과 같이 수정했습니다.
- 96ac48bea52296ea9b8cb14a3039496a9eb1d7e8

2024-05-16 07:07 UTC, Moorisong commented on apps/client/components/MyHeader/index.tsx
> +      <SideMenu doLogOut={doLogOut} hideSideMenu={hideSideMenu} login={login} />
감사합니다. 이벤트 형식 네이밍 습관화 하겠습니다!
- 80c765e90d70a46c487543dfa59f45c402b6b7ff

2024-05-16 07:15 UTC, Moorisong commented on apps/client/components/ui/types.d.ts
> +  type Wrap = {
이럴수가..처음 알았습니다..ㅠ 감사합니다.
다음 피처 개발에서 전부 적용하도록 하겠습니다.

2024-05-16 16:05 UTC, the1975 approved these changes

2024-05-18 09:36 UTC, the1975 commented
이거 머지 안하나요?

2024-05-18 10:42 UTC, merged