[client] 코드 리팩토링
Mong-Bit/mongbit_fe_next_v2 pull request #55
Opened 2024-05-09 11:53 UTC by Moorisong

- 변수 명, 컴포넌트 명 수정
- 컴포넌트 파일 정리
   - 위치 이동
   -  컴포넌트 분리 및 통합
- 이슈
  - #53

2024-05-10 08:07 UTC, the1975 requested changes

2024-05-10 08:07 UTC, the1975 commented on apps/client/components/MbtiTestItems/index.tsx
> +export function TestItemWithCount({ imageUrl, squareText, countData }: Ui.TestItemBigProp) {
지금 TestItemBig, Small, WithCount 3개가 있는데 이거 한개 모듈로 만들 수 있지 않나요? UI가 크게 다르지 않아보이는데요.

2024-05-10 08:07 UTC, the1975 commented on apps/client/utils/mbtiTest.ts
>      data.setMbtiTestData((prev: Model.MbtiTest[]) => ({
이거 prev 타입이 `Model.MbtiTest[]` 배열이 맞나요? 아래 보면 객체에 `...prev`로 스프레드 해주고 있는데

2024-05-13 02:33 UTC, Moorisong commented on apps/client/utils/mbtiTest.ts
>      data.setMbtiTestData((prev: Model.MbtiTest[]) => ({
현재 수정님이 전체 타입 리팩토링 중입니다. 추후에 수정하도록 하겠습니다.

2024-05-13 02:49 UTC, Moorisong commented on apps/client/components/MbtiTestItems/index.tsx
> +export function TestItemWithCount({ imageUrl, squareText, countData }: Ui.TestItemBigProp) {
한개 모듈로 만들라는 말씀의 의미가,
하나의 함수에서 props을 조건으로 사용해서 다르게 return 하라는 걸까요?

2024-05-14 05:25 UTC, Moorisong commented on apps/client/components/MbtiTestItems/index.tsx
> +export function TestItemWithCount({ imageUrl, squareText, countData }: Ui.TestItemBigProp) {
감사합니다. 다음과 같이 반영했습니다.
- e777309b896fa7c42fb744396fbc9676e08f52b7

2024-05-15 11:57 UTC, the1975 commented on apps/client/components/CommentBody/index.tsx
> +              $isModifying={isModifying[i]}
이런건 좀 미리 커밋하기 전에 확인해야하지 않나요?

2024-05-15 11:58 UTC, the1975 commented on apps/client/components/CommentBody/index.tsx
> +              $isModifying={isModifying[i]}
제가 잘 모르는건지 원래 컴포넌트 prop 이름인가요?

2024-05-15 11:59 UTC, the1975 commented on apps/client/components/CommentBody/index.tsx
> +              $isModifying={isModifying[i]}
그리고 `isModifying[i]` 이거는 각 코멘트별로 수정중인 상태를 나타내는 것 같은데, 이런건 컴포넌트 개별적으로 관리해야 하지 않나요?

2024-05-15 12:06 UTC, the1975 requested changes

2024-05-15 12:06 UTC, the1975 commented on apps/client/components/MbtiTestItem/index.tsx
> +      {countDataArr?.map((el, i) => (
`countDataArr` 가 이미 위에 정적으로 선언되어있는데 optional chaining을 적용한 이유가 뭔가요?

2024-05-15 12:06 UTC, the1975 commented on apps/client/components/CommentArea/index.tsx
> +            <Image src={CommentImage.src} alt={IMAGE_ALT_STRING + '코멘트 아이콘'} fill sizes="100%" />
`IMAGE_ALT_STRING` 이거 객체 아닌가요?
```ts
export const IMAGE_ALT_STRING = {
  MONGBIT_TITLE: '몽빗 MBTI 심리테스트 ',
};

```

이거같은데..

2024-05-15 12:06 UTC, the1975 commented on apps/client/containers/main/index.tsx
> +        <p>고민할 틈은 안줄테니 일단 플레이하고 생각하기</p>
`안 줄 테니` 입니다.

2024-05-16 03:19 UTC, Moorisong commented on apps/client/components/CommentBody/index.tsx
> +              $isModifying={isModifying[i]}
맞습니다. 현재 수정님이 개별 컴포넌트에서 관리되도록 리팩토링 작업 중에 있습니다.

2024-05-16 03:26 UTC, Moorisong commented on apps/client/components/CommentArea/index.tsx
> +            <Image src={CommentImage.src} alt={IMAGE_ALT_STRING + '코멘트 아이콘'} fill sizes="100%" />
앗 실수입니다. 감사합니다. 수정 했습니다.
- 4fa4deca5271f92e8d4e16febb8d3a93faace901

2024-05-16 03:30 UTC, Moorisong commented on apps/client/components/MbtiTestItem/index.tsx
> +      {countDataArr?.map((el, i) => (
앗 실수였습니다. 수정했습니다. 감사합니다!
- 7ea18d792149c3f36b361187a2882e84d5b7d17a

2024-05-16 16:06 UTC, the1975 approved these changes

2024-05-16 16:40 UTC, merged