[client] type 정리 및 api response data type 적용
Mong-Bit/mongbit_fe_next_v2 pull request #57
Opened 2024-05-11 17:30 UTC by lucy0701

1. fetchData() : Props type 수정
2. types 폴더 내부 사용 될 타입 정리
3. services api요청 관련 함수들 정리
4. 타입과 services로직 매핑

2024-05-12 07:43 UTC, the1975 requested changes

2024-05-12 07:43 UTC, the1975 commented on apps/client/services/index.ts
> +export const fetchData = async <T>(url: string, method: Method, options?: Partial<FetchOptionProps>) => {
index 내부의 함수들을  services/util로 옮기고 index에서는
```ts
export * from './mbti.ts'
export * from './like.ts'
```
위와같은 패턴으로 사용하면 될 듯 합니다.

2024-05-12 07:43 UTC, the1975 commented on apps/client/services/kakao.ts
> +const headers = createHeaders();
headers를 요청마다 새로 생성해야 하지 않나요? 초기에 생성해서 가지고있어버리면 토큰이 만료되더라도 그대로 가지고 있을 것 같은데 문제가 없나요?

2024-05-12 07:43 UTC, the1975 commented on apps/client/types/comment.ts
> +  commentDTOList: Comment[];
이거는 서버에서 내려오는 필드명인가요?

2024-05-12 07:43 UTC, the1975 commented on apps/client/types/styled.ts
> +export interface InitStyles {
궁금한게 이거 `React.CSSProperties` 에 이미 다 정의되어있지 않나요?

2024-05-12 07:43 UTC, the1975 commented on apps/client/types/util.ts
> +};
여기도 eol 빠져있네요. PR 올리고 매번 체크하던지 하셔야 할 것 같습니다.

2024-05-12 07:51 UTC, lucy0701 commented on apps/client/types/comment.ts
> +  commentDTOList: Comment[];
넵

2024-05-12 07:52 UTC, lucy0701 commented on apps/client/services/index.ts
> +export const fetchData = async <T>(url: string, method: Method, options?: Partial<FetchOptionProps>) => {
감사합니다 :-) 적용하겠습니다

2024-05-12 07:59 UTC, lucy0701 commented on apps/client/services/kakao.ts
> +const headers = createHeaders();
맞습니다! 바로 반영하겠습니다

2024-05-12 08:07 UTC, lucy0701 commented on apps/client/types/util.ts
> +};
정정 완료 했습니다 ! 확인 잘 하도록 하겠습니다

2024-05-15 11:51 UTC, the1975 commented on apps/client/services/index.ts
> +export const fetchData = async <T>(url: string, method: Method, options?: Partial<FetchOptionProps>) => {
`fetchData`도 같이 옮겨가면 괜찮겠네요~ index에서는 각 파일들을 export 하는 구문만 있는게 깔끔할 것 같아요

2024-05-15 14:52 UTC, lucy0701 commented on apps/client/services/index.ts
> +export const fetchData = async <T>(url: string, method: Method, options?: Partial<FetchOptionProps>) => {
이동 했습니다!
[c25cdd7](https://github.com/Mong-Bit/mongbit_fe_next_v2/pull/57/commits/c25cdd7a6974936fa457f770f1a646667fd216cb)

2024-05-15 14:54 UTC, the1975 approved these changes

2024-05-16 07:01 UTC, merged