[client] component / buttons
Mong-Bit/mongbit_fe_next_v2 pull request #58
Opened 2024-05-16 17:53 UTC by lucy0701

- FloatButton
- IconButton

2024-05-17 15:32 UTC, lucy0701 reviewed
-24.05.19 까지 적용 완료 하겠습니다

2024-05-17 15:32 UTC, lucy0701 commented on apps/client/components/Buttons/FloatButton/index.tsx
> +      backgroundColor=" #ffc42fd7"
Base.Button  타입별 컬러 추가 
- theme.colors  : 사용 할 버튼의 컬러 정의 (호버 컬러 포함)

2024-05-17 15:32 UTC, lucy0701 commented on apps/client/components/Buttons/IconButton/index.tsx
> +const Button = styled.button<Pick<Props, 'width' | 'height' | '$isOn'>>`
Base.Button 활용 하기

2024-05-17 15:37 UTC, lucy0701 commented on apps/client/components/Buttons/FloatButton/FloatMenuButton.tsx
> +  z-index: 100;
FloatButton : z-index랑 맞추기
SideBar보다 낮게 설정하기

2024-05-17 16:01 UTC, lucy0701 commented on apps/client/components/Buttons/FloatButton/FloatMenuButton.tsx
> +  menuOptions: {
MenuOptions[] : type 따로 util로 빼기 
- floatMenuOptions[] 생성 시 사용 해야함

2024-05-17 16:11 UTC, the1975 requested changes

2024-05-17 16:11 UTC, the1975 commented on apps/client/components/Buttons/FloatButton/FloatMenuButton.tsx
> +    onClick: () => void;
기본 베이스인 버튼 prop을 정의해놓고 가져와서 ButtonProps[] 만 해줘도 될 것 같네요.

2024-05-18 14:29 UTC, lucy0701 commented on apps/client/components/Buttons/FloatButton/FloatMenuButton.tsx
> +  menuOptions: {
버튼명 변경완료 했습니다!
[6c80852](https://github.com/Mong-Bit/mongbit_fe_next_v2/pull/58/commits/6c80852ded9495804f412531346532d2f420433d)

2024-05-18 14:45 UTC, lucy0701 commented on apps/client/components/Buttons/FloatButton/FloatMenuButton.tsx
> +    onClick: () => void;
타입 추가 및 적용 완료 했습니다!
[36e0ad1](https://github.com/Mong-Bit/mongbit_fe_next_v2/pull/58/commits/36e0ad1384c445fd58bac6df9effc4cba781c50f)

2024-05-18 14:45 UTC, lucy0701 commented on apps/client/components/Buttons/FloatButton/FloatMenuButton.tsx
> +  menuOptions: {
[36e0ad1](https://github.com/Mong-Bit/mongbit_fe_next_v2/pull/58/commits/36e0ad1384c445fd58bac6df9effc4cba781c50f)

2024-05-18 14:57 UTC, lucy0701 commented on apps/client/components/Buttons/FloatButton/FloatMenuButton.tsx
> +  z-index: 100;
[7064d97](https://github.com/Mong-Bit/mongbit_fe_next_v2/pull/58/commits/7064d9763b90eaac9410d667e85c6ed11b14cf79)

2024-05-18 15:05 UTC, lucy0701 commented on apps/client/components/Buttons/IconButton/index.tsx
> +const Button = styled.button<Pick<Props, 'width' | 'height' | '$isOn'>>`
[f4c2ce5](https://github.com/Mong-Bit/mongbit_fe_next_v2/pull/58/commits/f4c2ce5403d9c43ce7eb08fd1ea423772605683c)

2024-05-18 15:55 UTC, lucy0701 commented on apps/client/components/Buttons/FloatButton/index.tsx
> +      backgroundColor=" #ffc42fd7"
[cca3bef](https://github.com/Mong-Bit/mongbit_fe_next_v2/pull/58/commits/cca3bef52d69beb8c1301c5c4baeeba03333c4b3)

2024-05-19 04:32 UTC, the1975 commented on apps/client/components/Buttons/FloatButton/FloatMenuButton.tsx
> +  menuOptions: {
그게 아니고 menuOptions prop명이 buttons가 적절하다는 얘기였습니다.. 컴포넌트명도 마찬가지긴 하네요

2024-05-19 04:33 UTC, the1975 commented on apps/client/types/util.ts
> +}
eol 빠졌네요

2024-05-19 04:33 UTC, the1975 commented on apps/client/types/styled.ts
> +  // 마이그레이션 종료후 '?' & backgroundColor 삭제 예정 (현재 미적용 컴포넌트 오류 방지)
이런건 
// TODO: 마이그레이션 종료후 '?'...
로 주석 prefix 달아주면 좋을 듯 합니다.

2024-05-19 04:45 UTC, lucy0701 commented on apps/client/components/Buttons/FloatButton/FloatMenuButton.tsx
> +  menuOptions: {
헙..적용완료 했습니다
[f6a07b7](https://github.com/Mong-Bit/mongbit_fe_next_v2/pull/58/commits/f6a07b7795fd54a20e8467990c0a2ae6440a18bf)

2024-05-19 04:45 UTC, lucy0701 commented on apps/client/types/util.ts
> +}
추가했습니다
[f6a07b7](https://github.com/Mong-Bit/mongbit_fe_next_v2/pull/58/commits/f6a07b7795fd54a20e8467990c0a2ae6440a18bf)

2024-05-19 04:52 UTC, lucy0701 commented on apps/client/types/styled.ts
> +  // 마이그레이션 종료후 '?' & backgroundColor 삭제 예정 (현재 미적용 컴포넌트 오류 방지)
넵 추가했습니다!

2024-05-19 09:42 UTC, the1975 approved these changes

2024-05-19 11:58 UTC, merged