[client] service api 업데이트
Mong-Bit/mongbit_fe_next_v2 pull request #75
Opened 2024-05-19 13:58 UTC by Moorisong

**1. 기존 api 요청 함수를 업데이트된 /services api들로 업데이트 했습니다.**

**2. 로그인 요청 api 함수 생성**
로그인 요청 api의 응답 값에 headers를 가져와야 합니다.
기존 fetchData는 headers를 반환하지 않습니다.

- fetchData에 조건을 걸어서 다르게 return 함
- 로그인 fetch 함수를 하나 새로 만들어서 사용함

위의 두가지 방식 중 고민하다가 2번을 선택했습니다.

**3. getHeaders -> createHeaders로 변경했습니다.**

2024-05-19 14:12 UTC, the1975 requested changes

2024-05-19 14:12 UTC, the1975 commented on apps/client/components/CommentArea/index.tsx
> +    await submitCommentAPI(headers, body);
자잘한거긴 하지만 이거 POST 요청인 것 같은데 method 이름이랑 같이 맞추는게 좋아보입니다.
postCommentAPI로

2024-05-19 14:12 UTC, the1975 commented on apps/client/services/util.ts
> +export const fetchLoginData = async <T>(url: string, method: Method, headers: Headers) => {
2번으로 사용한 이유가 뭔가요? 굳이 fetch가 두개일 필요는 없어보입니다.
1번도 조건으로 줄 필요 없이 항상 내려주는 형식이 나아보이네요.

2024-05-19 14:12 UTC, the1975 commented on apps/client/utils/mbtiTest.ts
> +  fetchData(fetchOption.url, fetchOption.method, { headers: fetchOption.headers }).then((response) => {
fetchLoginData 사용하려고 했던거 아닌가요? 일단 이거와 관계없이 fetchData 한개로 사용하는게 좋습니다.

2024-05-19 14:15 UTC, Moorisong commented on apps/client/services/util.ts
> +export const fetchLoginData = async <T>(url: string, method: Method, headers: Headers) => {
조건 줄 필요없이 항상 Headers와 함께 내려주는 형식이 나아보인다는 말씀이실까요?

2024-05-19 14:21 UTC, the1975 commented on apps/client/services/util.ts
> +export const fetchLoginData = async <T>(url: string, method: Method, headers: Headers) => {
네 맞습니다

2024-05-19 14:24 UTC, the1975 commented
그리고 개인브랜치면 굳이 feature 안붙이고 ksh/ 으로 시작해도 됩니다.

2024-05-24 05:27 UTC, Moorisong commented on apps/client/components/CommentArea/index.tsx
> +    await submitCommentAPI(headers, body);
네 함수명 수정하였습니다.
- 14573047b4b573d17077b1f2ca95316f8949f30c

2024-05-24 06:15 UTC, Moorisong commented on apps/client/services/util.ts
> +export const fetchLoginData = async <T>(url: string, method: Method, headers: Headers) => {
data와 headers를 함께 내려주도록 변경했습니다.
- 486e0fc790abef4413f2b315dee0268e1d138ced

2024-05-24 06:15 UTC, Moorisong commented on apps/client/utils/mbtiTest.ts
> +  fetchData(fetchOption.url, fetchOption.method, { headers: fetchOption.headers }).then((response) => {
네 함수 하나로 통일했습니다 감사합니다.
- 486e0fc790abef4413f2b315dee0268e1d138ced

2024-05-24 08:59 UTC, lucy0701 commented on apps/client/services/util.ts
>    return {
반환 데이터 타입 변경도 부탁드려요!

2024-06-02 04:05 UTC, Moorisong commented on apps/client/services/util.ts
>    return {
늦어서 죄송합니다. 변경 했습니다.
- 547020ddffc756dc7022d1e35e79be7c0bff007a

2024-07-01 08:58 UTC, merged